# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

resources:
 repositories:
  - repository: summer-parent # The name used to reference this repository in the checkout step
    type: github
    endpoint: hummel
    name: mhus/summer-parent

steps:
- checkout: self
- checkout: summer-parent
- script: |
    echo Hello, world!
    lsb_release -d
  displayName: 'Hello'
- script: |
    cd ../summer-parent
    echo $(Build.BuildId) > touch.txt
    git add touch.txt
    git commit -m"Pipeline commit $(Build.BuildNumber)"
    git push
  displayName: 'commit summer-parent'


